### ISSUE TITLE
Add support for identityToken field to AuthConfig

### ISSUE THREAD

**Issue by Redent0r** [keirlawson/docker_credential#13]
Propose to add support for [identityToken](https://github.com/moby/moby/blob/master/api/types/registry/authconfig.go#L30) field to [AuthConfig](https://github.com/keirlawson/docker_credential/blob/master/src/config.rs#L7)

**Comment by keirlawson** [comment]
What's the  usecase for this?

**Comment by Redent0r** [comment]
@keirlawson There's at least one way that I know of that you can authenticate to a  registry without setting the `auth` field. That is using ⁠[az acr login](https://learn.microsoft.com/en-us/cli/azure/acr?view=azure-cli-latest#az-acr-login). Doing this will only set the `identityToken` field in the docker config. The usecase that I have, and others may, is to be able to read this token from the config (set be `az acr login`) and use it to authenticate to registry inside rust app.
